### ISSUE TITLE
Нейминг

### ISSUE THREAD

**Issue by Red-Cat-Fat** [StrangeChestnut/Clicker#1]
Если делаешь ScriptableObject, то и именуй его так, чтобы было понятно, что это ScriptableObject
https://github.com/StrangeChestnut/Clicker/blob/99692ad0df906a059959499dd54c6f630bef684a/Assets/Scripts/Score.cs#L7

**Comment by StrangeChestnut** [comment]
Сделал его ScoreScriptableObject, но изначально я не хотел этого делать, потому шо такое название кажется слишком громоздким, хе

**Comment by Red-Cat-Fat** [comment]
Название должно отображать предназначение класса. ScoreScriptableObject не такое уж длинное название

**Comment by StrangeChestnut** [comment]
Понял, принял
