### ISSUE TITLE
Нейминг

### ISSUE THREAD

**Issue by Red-Cat-Fat** [StrangeChestnut/Clicker#2]
Приватные переменные должны начинаться с _
https://github.com/StrangeChestnut/Clicker/blob/99692ad0df906a059959499dd54c6f630bef684a/Assets/Scripts/ScoreHitAction.cs#L7
Это не ошибка кода, а культура кода

**Comment by StrangeChestnut** [comment]
Упс, про культуру я знаю, не туда смотрел видимо в этот момент :), исправил

**Comment by Red-Cat-Fat** [comment]
Будь внимательнее
