### ISSUE TITLE
Инкапсуляция и снова неймнг

### ISSUE THREAD

**Issue by Red-Cat-Fat** [StrangeChestnut/Clicker#3]
А была ли необходимость делать эти переменные публичными? Может стоило сделать private с атрибутом [SerializeField]?
https://github.com/StrangeChestnut/Clicker/blob/99692ad0df906a059959499dd54c6f630bef684a/Assets/Scripts/Spawner.cs#L8-L12
Interval, From, To тоже не совсем понятные названия. Интервал может быть разным, от и до чего можно вообще перечислять бесконечно. Лучше всегда конкретилировать, ибо возможно твой код будет поддерживать либо дурак, либо джун, который не так всё сделает

**Comment by StrangeChestnut** [comment]
Уф, заренэймил

**Comment by Red-Cat-Fat** [comment]
Так а ссылку на исправляющий комит где взять?

**Comment by StrangeChestnut** [comment]
Можно было в описании к коммиту указать номер Issue, но я об этом только узнал
https://github.com/StrangeChestnut/Clicker/commit/13eba2e8e757d9eced89304b2633cb65c19d784e

**Comment by Red-Cat-Fat** [comment]
Во, уже лучше
